### ISSUE TITLE
Pitch is doubled after saving to wave

### ISSUE THREAD

**Issue by charlesbrandt** [casebeer/audiogen#4]
When I run the following script using audiogen, the output wave file has a pitch that is double the specified frequency, and the silence duration is only .5 second instead of the expected 1 second. I've had a hard time tracking down the culprit for this... any ideas?

    import audiogen
    import itertools

    def silence_tone(silence):
        """
        parameter is length of time in seconds
        """
        return itertools.chain( audiogen.silence(silence), audiogen.tone(440), )

    def make_wave(destination):

        output = audiogen.util.mixer(
            # first parameter is all of the source generators
            ( silence_tone(0), silence_tone(1), ),
            #next is a list of parameters for each channel
            #to specify levels for each of the previous source generators:
            (
                (audiogen.util.constant(1), audiogen.util.constant(0)),
                (audiogen.util.constant(0), audiogen.util.constant(1)),
                )
            )

        with open(destination, "wb") as f:
            #crop will set the maximum length of the file (so not infinite)
            audiogen.sampler.write_wav(f, audiogen.util.crop(output, 2.0))

    destination = "output.wav"
    make_wave(destination)

**Comment by konfiot** [comment]
Also got that kind of things sometimes

**Comment by casebeer** [comment]
@charlesbrandt, sorry I missed this! 

I'll take a look and try to reproduce. Thanks for the reports. 

My first guess is that it might have something to do with the global `sampler.FRAME_RATE` (managed with the `sampler.frame_rate` context manager), but that's just a stab in the dark for now.

**Comment by casebeer** [comment]
The issue was in the multiplexing code of the `mixer()` function: Each input channel was being consumed at a rate of one input sample per output channel per output sample. Thus two output channels caused the pitch to double. Duplicating the input generators prior to muxing fixed this. 

The fix is in master and should be pushed to PyPi. Thanks for the bug report.
